### PR TITLE
Editor tweaks 2

### LINKED ISSUE #36: "Update all styles" button
I think there should be a button for updating all styles (it would appear after checking all styles for updates).
When you check all styles for updates now, you still need to manually click the "Install update" button for each style.

### PR DESCRIPTION
**Pull request by tophf**
* **Editor: don't scroll sections into view on click**, see #71
* **Manager: "Apply all updates" button** closes #36

  How it works:
  1. *checkUpdateAll* hooks checkUpdate with a callback that counts styles that have an update, during the process the button is disabled and turns gray
  2. When the last style is checked, the button is re-enabled and *applyUpdateAll* button is displayed if there were styles with updates, its title also shows the number of updates
  3. When *applyUpdateAll* is clicked it's immediately disabled&grayed, disappears after 1 second

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
The update button will look weird if there's 1 ("Apply all 1 updates"). It's even worse in other languages with multiple plural forms. I'd prefer to avoid the issue altogether and just have it "Apply all updates".

**Comment by tophf** [comment]
Rebased the PR to upstream.

> just have it "Apply all updates".

Done.

**Comment by hideheader** [comment]
The `table` should remain a `table`. A `table` can vertically align corresponding elements and auto-magically choose a width that accommodates all of them; it's the appropriate representation of tabular information such as label:value pairs. It's easy enough to change `display` of `table`, `tr`, and `td` elements to produce other layouts in CSS; it's not easy at all to reconstruct tabular behavior *post hoc*, and impossible after the proposed change because the necessary containment has been removed.

**Comment by tophf** [comment]
@hideheader, 1) the options aren't tabular data as a whole, only those with inputs 2) css `display: table-cell` adjusts the widths perfectly where appropriate and 3) it is a proper way of doing this when dealing with hybrid data which is \*not* [a table](http://upload.wikimedia.org/wikipedia/commons/9/98/Rollup_table.png) *per se*.

**Comment by hideheader** [comment]
I've explained what we lose with your changes. What do we gain?

**Comment by tophf** [comment]
> I don't see any improved responsiveness.

It's noticeable when opening a style in a new window.

> Automatically substituting "!important" for an exclamation point is a nuisance, not a feature. I don't see a means to disable it.

It only works in properties, outside of strings. How is it a nuisance? Please, be more specific. Currently I don't see how it can be a nuisance.

>I've explained what we lose with your changes. What do we gain?

I've answered that we lose nothing, visually it's the same. As for what we gain I believe I answered that too: `Using html-table for layout is plain wrong.`

**Comment by hideheader** [comment]
> How is it a nuisance? Please, be more specific.

I can touch-type. Any "feature" that inserts text while I'm typing is a nuisance. That's the same reason  no doubt why `closebrackets` is an option in Firefox's editor and not always enabled.

> It's noticeable when opening a style in a new window.

Not on slow machines. Perhaps I'll see a difference on the i7.

> we lose nothing, visually it's the same

We lose the flexibility to modify the layout via a user stylesheet. You've removed the container elements and substituting breaks to achieve the same look, but if it looks the same what was gained by sacrificing flexibility in styling the interface?

> As for what we gain I believe I answered that too: Using html-table for layout is plain wrong.

"It is because it is" is not an explanation.

**Comment by tophf** [comment]
> Any "feature" that inserts text while I'm typing is a nuisance.

Okay, I'll try to hook it to the autocomplete hotkey

> You've removed the container elements

I'll add DIVs, not a problem, nothing will be sacrificed.

> "It is because it is" is not an explanation.

Please. You can google those discussions for yourself.

**Comment by tophf** [comment]
I'll squash these fixup commits when we agree on them.

**Comment by tophf** [comment]
Okay, this is looking good, I'll squash these fixup commits when we agree on them.

**Comment by JasonBarnabe** [comment]
If you could limit the PRs to implementing one feature/bug fix each that would make it much easier to review. You can leave this one as is.

- I think you can drop the tooltip on Edit button. This is fairly standard behaiour, and the tooltip looks silly because of the multiline.
- The "reuse existing tab" behaviour doesn't work on the edit links on the manage window.
- You should be able to open a bunch of "new style" tabs.
- Can you add classes to the containers for each option? I imagine that would be useful to people.
- I don't think having a `dl` with one item makes sense.
- If you don't have "Extensions" open, right-clicking Stylish and then Options opens it now.

**Comment by tophf** [comment]
* [x] dropped the toolip
* [x] fixed the re-use behavior
* [x] unlimited new style tabs
* [x] removed the OptionsV2 because Chrome can't be fooled into not opening the extensions tab, it's the way they implemented the UI :rage:
* [ ] Still working on editor options as I want good integration with responsive UI (737px media-width). I will submit it as a separate PR.

**Comment by tophf** [comment]
CodeMirror's scroll-jump probem on click was [fixed](https://github.com/codemirror/CodeMirror/commit/35a96182ede54c935cca7231365fe180092e32e2) right after 5.0 release, and it actually works, so if it'll be merged, my ugly hack (the already merged c084ea3973b48050fd5311bd68fc8273b0b701ed) can be reverted.

**Comment by JasonBarnabe** [comment]
Once they come out with a release, I will.

**Comment by tophf** [comment]
Rebased onto master.

> Once they come out with a release, I will.

Okay, I'll remind to revert that commit then or will submit a PR.

**Comment by tophf** [comment]
Support for responsive layout: [before](https://i.imgur.com/6g9vdGL.png), [after](https://i.imgur.com/mEbGPHp.png).

**Pull request merged**
