### PR TITLE
Menu item order

### PR DESCRIPTION
**Pull request by hideheader**
Append 'New style' to the existing menu items, for continuity with the previous layout.

### CODE REVIEW

**Comment by hideheader** [comment]
Stupid Git... hub. There is really only one commit here. The "Merge pull request" commit was just me pulling in your recent changes. I don't know why Github didn't include just the commit that followed it.

**Comment by JasonBarnabe** [comment]
Your CSS change isn't correct. `.actions` is the Edit/Disable/Delete stuff, so now Find/Write/Manage are all smushed together.

**Comment by JasonBarnabe** [comment]
Or maybe this just assumes #30 is in...

**Comment by hideheader** [comment]
No, it's just plain wrong. Somehow two successive commits ended up on two different branches instead of together on their own branch. Pruning...

**Pull request closed without merging**
