### PR TITLE
Apply styles to popup on change/disableAll

### LINKED ISSUE #92: Pop-up is not immediately affected by enabling/disabling style that affects it
e.g. https://userstyles.org/styles/1/stylish-test-style, you have to close and re-open the pop-up for the change to take effect.

### PR DESCRIPTION
**Pull request by tophf**
Closes #92

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
Why don't the normal "methods" in `apply.js`

**Comment by tophf** [comment]
Because popup isn't a tab and it doesn't receive messages from `notifyAllTabs()`

**Comment by JasonBarnabe** [comment]
With the PR as is, doesn't it mean that the `updatePopup` events will run for things other than the pop-up as well, meaning they'll happen twice?

What if you changed `notifyAllTabs` to also notify the pop-up? You could have something in popup.js that listens for `updatePopup` and then refires it with the actual reason.

**Comment by tophf** [comment]
It doesn't fire twice, I've checked it in the debugger.

Currently `updatePopup` event is fired only when it's really needed, so for example it's not fired for `prefChanged` event.

**Comment by JasonBarnabe** [comment]
It looks like every `updatePopup` message is done at the same time as `notifyAllTabs`, so I'd prefer `notifyAllTabs` to be updated just to fire it itself. It's OK if it'll fire for things the pop-up doesn't care about.

To avoid duplication in `apply.js`, why not just add this to the top of the listener?

```js
// Handle special request just for the pop-up
if (request.reason == "updatePopup") {
  request.method = request.reason;
}
```

**Comment by tophf** [comment]
Those are good points. 
Updated the code.
Rebased on master.

**Pull request merged**
