### PR TITLE
Add SVG icon, compress PNG icons with pngquant+optipng

### PR DESCRIPTION
**Pull request by tophf**
Now the logo is scaled to the header width by default, the size can be changed via CSS without compromising quality.

<sup>TODO: use SVG icon in manifest.json once Chrome implements [the feature](https://code.google.com/p/chromium/issues/detail?id=29683) (could take another 5 years).</sup>

header

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
Image in manage doesn't work for me with this.

**Comment by tophf** [comment]
Tried on a clean Chrome 41 stable - everything's fine, as well as on Chrome 43 dev. AFAIK Chrome supports svg images since the early days.

**Comment by JasonBarnabe** [comment]
I'm on 41 as well.

I do see `Resource interpreted as Image but transferred with MIME type image/svg+xml-compressed: "chrome-extension://igdlooladkdocklgkionbogoaehcpdnd/logo.svgz".` in the console. If I try to access it directly, Chrome "downloads" it.

**Comment by tophf** [comment]
linux?

**Comment by JasonBarnabe** [comment]
Yup. Ubuntu.

**Comment by tophf** [comment]
I don't have a linux box right now, so I've embedded the svg in html, try it.

**Comment by JasonBarnabe** [comment]
The image works now.

Right after the shift to one column, the image is wayyyy too big.

**Comment by tophf** [comment]
> Right after the shift to one column, the image is wayyyy too big.

Yeah, impressive!
I've added `max-width` to the responsive CSS section. Should I squash these two fixup commits and rebase?

**Pull request merged**
