### PR TITLE
Add search, code folding to editor

### PR DESCRIPTION
**Pull request by hideheader**
Each section's search is independent of the others, which is a real nuisance. The sections' editors should be yoked together with a common search interface.

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
I don't understand this change. Before, if I did Ctrl+F, I got Chrome's search thingy which does search all the sections. Now, if the focus is inside one of the code boxes, I get CodeMirror's search box, which only searches that box. This seems contrary to what you described above.

**Comment by hideheader** [comment]
https://forum.userstyles.org/discussion/34496/stylish-chrome-1-1-update-suggestion#Comment_73759

I guess that's why it hasn't been fixed it before now.

**Comment by JasonBarnabe** [comment]
> Each section's search is independent of the others, which is a real nuisance. The sections' editors should be yoked together with a common search interface.

Maybe I get it now. This describes the situation *after* the PR, I assume.

**Comment by hideheader** [comment]
Yes. Chrome's 'Find' sees just the edit buffer in every section, and can't Replace anything. The PR adds CodeMirror's search, which can Find and Replace all of the text in one section. The objective is to coordinate the CodeMirror instances so that Find and Replace behaves as if the sections were part of a single edit buffer, and drive them from a single, common "Find" UI.

**Comment by JasonBarnabe** [comment]
I added the 5.0 version of these in https://github.com/JasonBarnabe/stylish-chrome/commit/b4173d68f6312300ab761f5454d7a8fb230d2bce, along with match brackets and lint (with warnings off).

**Comment by hideheader** [comment]
Match brackets is always on, or is there a preference to disable it?

**Comment by JasonBarnabe** [comment]
Always on. Didn't seem so annoying that it needed a pref.

**Comment by hideheader** [comment]
Perhaps if you'd used the editor at all you'd see it differently.

**Comment by JasonBarnabe** [comment]
You sure you know what match brackets is? It turns the starting/ending bracket a different color when your cursor is on the associated ending/starting bracket. The editor in Firefox does it too (though with a border rather than a color).

It's not the thing where it automatically adds the ending bracket when you type the starting bracket.

**Comment by hideheader** [comment]
Oh, thank goodness. Yes, I thought you'd added the hated `closebrackets` thing. Apologies.

**Pull request closed without merging**
