### PR TITLE
Editor: fixes

### PR DESCRIPTION
**Pull request by tophf**
* Correctly determine when to save the window size on tab close

  Previously the window size was overwritten with wrong values in case the only tab in Chrome window was the Manage styles page and then the Edit style page was opened by clicking some style's Edit button.

P.S. The PR has a generic name in case it will be stalled for a month and I'll find another bug to fix :D

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
If you set Stylish to use new windows, then opened a New Style window, saved it, and closed, then wouldn't `window.history.length` be > 1?

**Comment by tophf** [comment]
Ah, indeed.
I'll fix it by eliminating page reload on save.

**Comment by tophf** [comment]
Fixed.

**Comment by tophf** [comment]
Ugh, the size won't be saved if you open a style editor (via Add or Edit existing style), then go "back to manage", then edit another style. I'll see if this can be fixed without overcomplicating the code.

**Comment by tophf** [comment]
Done.

**Pull request merged**
