### PR TITLE
Update CSSLint and CodeMirror

### PR DESCRIPTION
**Pull request by tophf**
- **CodeMirror 5.18.2**  
  and addons
- 3 post-update commits were reapplied: lint-addon rule selection and speedups  
   
- **CSSLint 1.0.2**
  'worker' build version is used that doesn't break CodeMirror addons and exposes parserlib we need for mozilla-import functionality.
- edit.html and .js are updated accordingly  
   
- **Bugs fixed in edit.js:**
  - Correctly remove sections in initWithStyle after update
  - Don't re-run setupGlobalSearch to keep originalCommand bindings
     
- **Improvement in edit.js**:
  - Don't reload editor upon styleUpdated right after saving

### CODE REVIEW

**Comment by tophf** [comment]
Found some small bugs, fixed them here as well.

**Comment by Mottie** [comment]
I'd like to suggest that the linter get switced from [CSSLint](https://github.com/csslint/csslint) (last update Jul 19) to [Stylelint](https://github.com/stylelint/stylelint) (updated today).

Mostly because Stylelint supports CSS variables. There is also a "suggestion" to merge the libraries in https://github.com/CSSLint/csslint/issues/668.

**Comment by tophf** [comment]
Wow, the npm package is huge with lots of external dependencies - 27MB after `npm install stylelint` in a new folder. There's no single bundle build receipt, I see someone's attempt at https://github.com/m-allanson/stylelint-browser-demo - 1.5MB js bundle without plugins. I'm not familiar with packaging so I'd wait until the merger is finalized as the CSSLint developers will make sure there is a single-file bundle.

**Comment by silverwind** [comment]
Yeah, 1.6 MB is what I get when I [browserify](https://github.com/substack/node-browserify) stylelint. You'd also want a rule config, like [stylelint-config-standard](https://github.com/stylelint/stylelint-config-standard).

**Comment by Mottie** [comment]
Well, I know the main author of CSSLint is busy. If you look at the repository, there are 158 open issues and 21 PRs. In that issue I linked discussing the merging of the two linters, only two of the five CSSLint admin responded.

The main reason I even brought this up is because of CSS variables. This issue (https://github.com/CSSLint/csslint/issues/538) was opened just over two years ago with no responses from any of the admin.

So yeah, Stylelint is huge, but it might be worth it in the long run.

**Comment by tophf** [comment]
First I'll convert the editor to a single block a-la classic Stylish in Firefox, and there are some complications that need to be addressed.

**Comment by Mottie** [comment]
Sorry, I didn't think it would be easy. Should we open a new issue?

**Pull request closed without merging**
