### PR TITLE
Copy user styles into dynamic `IFRAME`s

### PR DESCRIPTION
**Pull request by hideheader**
One MutationObserver listens for `IFRAME` additions and copies the existing `STYLE.stylish` elements into the new frames. A second MutationObserver listens for `STYLE.stylish` additions and deletions and copies `STYLE`s or removes existing copies into existing frames.

Fixes https://github.com/JasonBarnabe/stylish-chrome/issues/3 ; some issues remain.

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
I don't understand the purpose of the `STYLE.stylish` observer. Surely it would be easier to change apply.js's `removeStyle` and `applySections` to handle iframes than it is to listen for those changes and apply them to iframes.

**Comment by hideheader** [comment]
Easier for who?

Evidently you *do* understand its purpose.

**Comment by JasonBarnabe** [comment]
Easier as in less code, easier to understand code, and probably quicker code. You'd be able to skip all the code you have to figure out what styles are changing because apply.js's functions already know.

**Comment by hideheader** [comment]
"Probably quicker"? Not enough to matter. I added eight `IFRAME`s [[1]](https://gist.github.com/hideheader/a3b136032503fabc2928) to http://ace.c9.io/#nav=embedding and toggled the associated test style [[2]](https://userstyles.org/styles/110701/test-anonymous-iframes-tinymce-et-al) on and off five times. Chrome spent 194ms in `observers.js`; 127ms of that was spent in `styleObserverReport`, writing to `console.log()` [[3]](https://forum.userstyles.org/uploads/FileUpload/20/2ae4744de66f2ad5ee370b68bf22aa.zip). That's 2.5ms/operation/frame with the debug info, 0.8ms without it.

I'm not gonna refactor the code just to make it more beautiful. Right now it's entirely separable from the rest of the codebase. I suggest that, barring any substantive issues,  you leave it that way for at least one release, and add a preference so that you can disable the observers if need be after 1.3.0 is distributed.
````javascript
if (!emergencyStop) observer.observe()
````
If they haven't broken in a year, you can knit the code into 1.4.0.

**Comment by JasonBarnabe** [comment]
Is the purpose of the observer on the `style class="stylish"` to react to what Stylish does when someone is installing/deleting/enabling/disabling styles, to react to the iframe being rewritten after it's added, or both?

**Comment by hideheader** [comment]
Yes, no, and no. The style observer watches Stylish add or remove `STYLE` elements in the top-level document, and adds or removes copies of those same `STYLE` elements in the `IFRAMES` that are already in the document. It's only a proxy for the existing content script, just as you said. The frame observer sees `IFRAME` elements being added to the top-level document, and copies the Stylish styles that are already in the top-level document into the new frames.

This style observer can't see DOM mutations in the frames. For that you need to start a second style observer on an element in the frame's `contentDocument`. If that document is rewritten or replaced, though, the observer won't be called. To see frame content get rewritten you need to watch `load` on the `IFRAME` element, or else watch `onCommitted` in the background script.

That gets messy. There can be 2-3 `load`s for each observer call - once when the `IFRAME` is inserted with a *pro forma* `<html><head/><body/></html>` document, again when the *pro forma* document is replace with (I think) `about:blank`, then again with the document that's finally in place when the MutationObserver is called. It can be sorted, but without a use-case it didn't seem worthwhile. 

There's an example intra-`IFRAME` observer and and `onLoad` listener in [my preceding commit](https://github.com/hideheader/stylish-chrome/commit/1bcb72dabc4ed6c93026e756b399da4f0da5125f). Enable them with `localStorage["observer.observeFrameContent"] = "true"` and `localStorage["observer.observeFrameLoad"] = "true"`, respectively.

**Comment by tophf** [comment]
Since `forEach` is [extremely slow](http://jsperf.com/for-vs-foreach/286#bs-chart-frame), this might be a problem on potentially large arrays like `mutations` and `addedNodes`. Unless some performance tests on very complex pages prove otherwise, it seems obviously reasonable to use a plain `for`-loop. The same goes for `filter` is also [extremely slow](http://jsperf.com/array-loop-vs-filter), even on Chrome 43 and `map` which is only [slightly slower](http://jsperf.com/map-vs-for-loop-performance/18).

**Comment by JasonBarnabe** [comment]
I've committed a version of this in https://github.com/JasonBarnabe/stylish-chrome/commit/908d7699443c2267266bdc379a97f602cce14033

The most significant difference is that I removed the observer for style add/remove and instead changed the logic in apply.js to recursively grab dynamic iframes. I also moved the iframe add/remove observer to apply.js to be able to reuse some of the functions there.

**Comment by hideheader** [comment]
And is it faster?

**Comment by tophf** [comment]
At least it has [a bug](https://github.com/JasonBarnabe/stylish-chrome/commit/908d7699443c2267266bdc379a97f602cce14033#commitcomment-10021692)!

**Comment by hideheader** [comment]
A fast bug?

**Comment by tophf** [comment]
:-)
Haven't tested it yet on mutation-heavy pages but I'll keep an eye on its performance...

**Comment by tophf** [comment]
Jason's 908d769 breaks automatic style injection on feedly.com, even though I've fixed the obvious typo. This PR, on the other hand, applied _instead_ of 908d769, doesn't break feedly.com. :thumbsup:

**Pull request closed without merging**
