### PR TITLE
Editor: maximize height of code boxes when possible

### PR DESCRIPTION
**Pull request by tophf**
Partially alleviates #1.

* Codeboxes are auto sized to contents on start but only when all of them would fit on one page.
* Maximum height == `window.innerHeight`, otherwise CodeMirror/browser lags a lot.
* Minimum height is calculated from css (currently 300px defined in codemirror.css)

P.S. This time I've split the new features into several mini-PRs as requested, but it seems counter-productive to me because I'll have to resolve conflicts in each PR after the previous one is merged (they all alter edit.js).

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
Doesn't seem to work here. I have two sections with one line each, yet on load they're the same size they've always been.

**Comment by tophf** [comment]
>Minimum height is calculated from css (currently 300px defined in codemirror.css)

**Comment by tophf** [comment]
BTW, that 300px default height is ~1.5x bigger than `10rem` previously used for plain text code boxes before CodeMirror was added. Should we override default CM's height then?

**Comment by JasonBarnabe** [comment]
Ah, I thought it would shrink fit too.

**Pull request merged**
