### PR TITLE
Edit style: autocomplete on Ctrl-Space using CodeMirror hint addon

### PR DESCRIPTION
**Pull request by tophf**
Two hint functions are used:

* **css-hint**.js: shows autocomplete hints for CSS properties _inside_ a { } rule definition
* **anyword-hint**.js: works _outside_ { } and uses all words in the code textarea - useful for classes, ids, etc.

### CODE REVIEW

**Comment by hideheader** [comment]
How do you disable it?

**Comment by tophf** [comment]
>How do you disable it?

And how do you disable it in Stylish for Firefox? Just don't press Ctrl-Space.

**Comment by JasonBarnabe** [comment]
Great, I was going to do this but was too lazy to figure out how to make it only work on Ctrl+Space.

anyword-hint.js seems pretty useless. If it only matched selectors it'd be good, but given this code:
```css
a { background-color: green;}
#fp{}
```
It suggests:
- fp (doesn't even include the #!)
- a
- background
- color
- green

**Comment by tophf** [comment]
I've removed the anyword-hint, also have had doubts about it. 

Maybe someday the css hinter will be enhanced by CodeMirror guys or someone will write a custom hint handler for Stylish...

**Comment by hideheader** [comment]
> Why would anyone press it anyway except for autocompletion?
It's currently the hotkey for another extension.

**Comment by tophf** [comment]
@hideheader, and what happens if you apply this PR and press Ctrl-Space? Also, Ctrl-Space is a universally used hotkey for auto-complete in code textboxes, so overriding it is like overriding Ctrl-F hotkey - someone may do it but it doesn't mean that Ctrl-F should be an option in a simple editor.

**Comment by hideheader** [comment]
Like references, hate hyperbole.

**Comment by tophf** [comment]
@hideheader, you apparently love yourself more than answering a direct question :grinning: Why don't you ask for an option to disable Ctrl-F, Ctrl-G, Ctrl-A and a few dozen of other hotkeys defined in CodeMirror?

**Comment by hideheader** [comment]
Is there a reason this feature can't be optional?

**Comment by tophf** [comment]
> Is there a reason this feature can't be optional?

Why don't you ask for an option to disable Ctrl-F, Ctrl-G, Ctrl-A and a few dozen of other hotkeys defined in CodeMirror?

**Comment by hideheader** [comment]
So that would be 'no', then.

**Comment by tophf** [comment]
Technically it's easy, but having an option just for one hotkey seems not right. I'm not convinced. Let's hear what @JasonBarnabe says.

**Comment by JasonBarnabe** [comment]
I see no reason why this should be an option. If you don't want autocomplete, don't press Ctrl+Space. If there's some other mystery extension screwing around in Stylish's edit window making Ctrl+Space do something else, well than that mystery extension will have to pick something else to trigger its mysterious functionality.

**Pull request merged**
