### PR TITLE
Editor: paste from Mozilla format

### LINKED ISSUE #31: Ability to paste full style, unprefixed @document
One thing that bothers me quite a bit about developing for Stylish on non-Firefox is that you have to unwrap the `@-moz-document` rules after pasting in a Style from an external editor.

I'd envision unprefixed `@document` rules which could be recognized by engines other than Firefox. It would make using an external editor and updating an stylesheet much more bearable for Chrome. While unprefixed `@document` isn't a standard yet, it probably will be at some time in the future, so the keyword would be pretty safe to use I think.

https://developer.mozilla.org/en-US/docs/Web/CSS/@document

### PR DESCRIPTION
**Pull request by tophf**
Closes #31

* CSSLint's [parser-lib](https://github.com/CSSLint/parser-lib) is used, with a few fixes ([PR for @keyframes](https://github.com/CSSLint/parser-lib/pull/157), nested doc handling is pending submission).
* `@-moz-document` and unprefixed `@document` are recognized
* The parser understands nested `@-moz-document` and puts a breaker `/*************/` between the parts of such divided outer sections
* Likewise, a global section is constructed from stuff outside of recognized sections
* If the global section only contains `@namespace url(http://www.w3.org/1999/xhtml);` and comments then it's not created.

A combined approach is used - parsing plus direct extraction of an entire section text in one go and a few regexps for detecting minor stuff. It seems failproof to me, moreover it'll require twice as much code for a pure parser approach, which is not necessarily more readable or failproof.

P.S. Now it seems possible to switch to a single-section layout, I think I'll start working on it lazily and then we'll have it as an option. And then maybe we'll make it the only choice if it proves to be reliable and more convenient (the latter would probably require some kind of visual indication of section's start and end, as well as `<`, `>` buttons and hotkeys to jump between sections).

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
What I'd like long-term is to give people the option of having Firefox-style single textarea style editing with `@document` or the current UI, and the ability to quickly switch between these modes. I'd also like to have styles installed with from text in the Mozilla format, just like in Firefox, rather than a separate JSON format as it is currently.

Do you think this change brings us "closer" to that end goal?

**Comment by tophf** [comment]
I think the PR obviously makes Stylish-chrome less of a nuisance UX-wise. The code might be later reused or refactored or whatever, it's a very minor issue from a user's viewpoint, there's not much code anyway.

**Comment by tophf** [comment]
Rebased on master.

**Comment by JasonBarnabe** [comment]
- Can you rework the To/From Mozilla Format buttons? Maybe give them their own section with the descriptive text already showing?
- Try this doc:
```css
@-moz-document domain(yahoo.com) {
/* yahoo.com 1 */
@-moz-document domain(my.yahoo.com) {
/* my.yahoo.com */
}
/* yahoo.com 2 */
}
```
- Pasting a multiline document into a single-line prompt box is kinda goofy. If you intend on fixing this later, then you could leave it for now.
- I think it makes more sense to replace the existing sections than to add to them.

**Comment by tophf** [comment]
1. Like this?
  ui-fs8
2. Everything's fine, the preceding comment is moved into the section as intended and documented in the function code. Userstyles usually (almost always) have a descriptive comment before @document.
3. Yes, but goofy is better than crashing the browser or making it totally unresponsive when pasting into a nice textarea which was what I've used initially.
4. I don't think so. After all we have a `Write new style` command exactly for this purpose.

**Comment by tophf** [comment]
4*. What if the user wants just to append a section he just wrote in Firefox? Of course, on the other hand, current behavior will make updating the entire style with many sections cumbersome. Do you think the latter happens more frequently?

**Comment by tophf** [comment]
3*. A non-read-only text box with tons of text is what makes the browser unresponsive.

**Comment by tophf** [comment]
I'll try wrapping the text area in CodeMirror, maybe it'll help.

**Comment by tophf** [comment]
Yay! This is great, CodeMirror handles it perfectly and the UI is now smart and sleek with an additional import-replace button as well. Thanks for the critique, helpful as always.

ui2-fs8

**Comment by tophf** [comment]
I'll do the same for import/export on the Manage page later.

**Comment by JasonBarnabe** [comment]
Much better.

- Can you switch to regular styling for the Import buttons?
- Maybe "Import and replace existing sections"?
- And put the buttons on the bottom. Right now they kinda look like tabs.
- Let me show you a nested example without comments:

```css
@-moz-document domain(google.com) {
    a {}
@-moz-document regexp(".*\\.html") {
    b{}
}
    c{}
}
```
This doesn't work right, as `b{}` should only be applied to something that's `google.com` **and** `.html`. This isn't supported by Stylish for Chrome anyway, and is probably pretty rare, so that's OK.

**Comment by tophf** [comment]
Done. The nesting case is also fixed.

**Comment by JasonBarnabe** [comment]
No, that doesn't fix the nesting case. Now what you're doing is making that code match google.com OR `.*\.html`. It should be AND. But as I said, this isn't supported anyway. Ignoring the nested block and pretending it's part of the parent seems most reasonable.

Some slight text changes:
- "Mozilla format" -> "Mozilla Format"
- "Paste the style in Mozilla format" -> "Paste the Mozilla-format code"
- "Overwrite the style" -> "Overwrite style"

**Comment by tophf** [comment]
>Ignoring the nested block and pretending it's part of the parent seems most reasonable.

Not if this is done silently.
Currently I've reverted the code so the nested sections are separate.
Maybe it's worth implementing the real thing?

**Comment by JasonBarnabe** [comment]
Nested `@document` rules are pretty rare. I'm fine with taking this without it. If you want to have a go at implementing them, go ahead, but I don't think it should be a high priority item.

**Pull request merged**
