### PR TITLE
Import/export all styles via JSON textbox

### PR DESCRIPTION
**Pull request by tophf**
Related issue: #2

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
I'm pretty mystified by the UI here, I'm not sure if there's something not working or missing or what. I see Import/Export on the manage screen. I press it and I get a dialog with an "Import" button and

**Comment by tophf** [comment]
Yep, the UI isn't very intuitive. What do you think of this:

1. import prompt: `Paste the styles in JSON format`, label above the code: `All installed styles in JSON format`

2. make two buttons: `Import` with the above text prompt (doesn't open a box with code), `Export` which opens a box without any buttons and titled as `All installed styles in JSON format` and of course that bunch of code.

**Comment by tophf** [comment]
Added the fix for #142 as it's merely one css property.

**Comment by tophf** [comment]
Implemented the 2nd idea. If it's ok please let me squash the fixup before merge.

**Comment by NAVEEDNOORKHAN** [comment]
Have you chat script for sharing?

**Comment by tophf** [comment]
Looks like we've got a spammer here.

**Comment by tophf** [comment]
Regarding the placeholder variables in localizable strings, is there something else that needs to be done like replicating them as is in all other languages or maybe the ruby script that pulls translations should be improved?

**Comment by tophf** [comment]
Oh, `jsonEquals()` had an ancient bug since the initial commit in 2012, I've fixed it.

**Comment by JasonBarnabe** [comment]
Does this require some other change? I get
```
manage.js:669 GET chrome-extension://igdlooladkdocklgkionbogoaehcpdnd/jsonlint/jsonlint.js net::ERR_FILE_NOT_FOUND
```
and there's no input on the Import modal, and Export gives
```
manage.js:685 Uncaught TypeError: Cannot read property 'json' of undefined
```

**Comment by tophf** [comment]
Added the missing jsonlint.js

**Comment by JasonBarnabe** [comment]
Already, works now.

I think the way it is could be made much more useful if you summarized and let the user choose what will happen. After the user enters the JSON, divide it in to styles to add, styles to change, styles to remove, with the style's name and a checkbox. The user can then uncheck whatever they don't want to happen. This way, you can send your styles to a friend and they can add it to their set without losing their own.

Some text explaining what's going on would be good. In the export screen, something like "This lists all your installed styles. You can use this code to back up your styles or send them to a new device."

Also, this has conflicts.

**Comment by docrinehart** [comment]
Bump! I reached out to @JasonBarnabe about doing something like this, but it seems there's already an open issue and even a PR for one implementation I was planning on. xD

**Comment by docrinehart** [comment]
Bump! I would like to see this merged!

**Comment by JasonBarnabe** [comment]
If you @docrinehart or @tophf fix the issues identified in my last comment I will merge this in. The main problem is that this is destructive without really giving an indication that it is. A page where the user can confirm what will happen (what will get added, changed, and deleted) would be best, but there may be other solutions.

**Pull request closed without merging**
