### PR TITLE
Support "breadcrumbs" new style links

### PR DESCRIPTION
**Pull request by hideheader**
Adds support for 'new style' links that resemble the page URL. Requires stylesheet support to enable it.
https://userstyles.org/styles/110560/breadcrumbs-new-style-links-stylish-for-chrome

Was https://github.com/JasonBarnabe/stylish-chrome/pull/30

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
This is better. I'd like to include the stylesheet in stock Stylish so feel free to make whatever changes that make it easier. Snazzy paths would be good too.

**Comment by hideheader** [comment]
Snazzy doesn't really work. `www.google.com/search?q=text-overflow...` looks good, and `developer.mozilla.org/en-US/docs/Web/C...` isn't bad, but `userstyles.org/` has no path at all to use for link text, and `github.com/hideheader/stylish-chrome/tre...` has so much link text that the poor domain is overwhelmed and lost.
breadcrumbs_google-1 breadcrumbs_mozilla-1 
breadcrumbs_no-path breadcrumbs_mostly-path

**Comment by JasonBarnabe** [comment]
OK, we'll leave off the snazzy path part, but add the CSS needed for the new display.

**Comment by hideheader** [comment]
By default the 'new style' links are displayed as a faux URL. This behavior can be disabled by setting `localStorage["popup.breadcrumbs"] = "false"`; the links should revert to "this URL" followed by a series of domains. By default "this URL" is displayed for the `url(...)` link. The URL path can be shown instead by setting `localStorage["popup.breadcrumbs.usePath"] = "true"`, but you'll need additional style rules to make it palatable. Using preferences uglifies the code, but if the feature should become a "feature" it can be persistently switched off from Developer Tools.

I replaced the spaces between links with soft hyphens (`U+00AD`) on `::before` so that the links would wrap in both cases without introducing gaps between the 'breadcrumbs' links. Chrome then treats the periods as if they ended sentences and therefore opportunities to wrap the text. A zero-width space (`U+200B`) precedes "/this URL"; otherwise Chrome will never break the line at that point. As a last resort Chrome will break between any two convenient characters ("`overflow-wrap: break-word`").

There are two issues with `:focus`. First, `:focus` and `:hover` decorations are identical, so the link decoration doesn't change if you hover over a 'new style' link while another is focused. This can be addressed in CSS by giving the two slightly different decorations. Second, irrelevant link text isn't grayed out when you tab through the links as it is when you hover over them. This requires code. When you hover over a link you also hover over its container. The container grays out its contents on hover, the links recolor themselves (and their downstream kin) on hover, thus the effect. Only one element can have focus, though, so the container can't "see" that one of the links it contains has focus unless a `focus` listener on the links sets a class on the container.

Some test URLs.
1. [www.cs.ucsb.edu](http://www.cs.ucsb.edu/~pconrad/topics/BackslashVsForwardSlash/) doesn't need to wrap.
2. [hyphenator.googlecode.com](http://hyphenator.googlecode.com/svn-history/r1027/wiki/en_CSS3Hyphenation.wiki) wraps after a dot.
3. `chrome-extension:` URLs wrap before the forward-slash.
4. [www.html-5.com](http://www-wowser.html-5.com/tags/wbr-tag/) wraps after a dash *within* the subdomain name (synthetic - change the link's `subdomain` value in Developer Tools)
5. `file:///` URLs have no subdomain (just sayin'...)

no-wrap-needed wrap-at-dot wrap-at-dash chrome-url-wraps file-url

**Comment by JasonBarnabe** [comment]
1. Can you drop the leading forward slash for `file:` URLs?
2. For `chrome-extension:` it looks pretty weird - just revert to "this URL" for that too.

**Comment by hideheader** [comment]
This stopped being amusing three nits ago.

**Pull request merged**
