### PR TITLE
Editor keymap help: press a hotkey to filter the list

### PR DESCRIPTION
**Pull request by tophf**
* fix CodeMirror.normalizeKeyMap - the bug is [reported](https://github.com/codemirror/CodeMirror/issues/3258) and fixed upstream.
* pressing a hotkey in the first inputbox will filter the list by this hotkey
  * ~~double Esc closes the popup~~
  * ~~double Tab switches to next input~~
  * ~~double Delete and double Backspace clear the input~~
* add localizable placeholders to inputboxes
* set initial focus to the command inputbox

screenshot-fs8 screenshot2-fs8

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
Just to limit confusion, I'd prefer that Esc and Tab do their normal thing and not do a keymap search. I don't think you need to handle double Delete or Backspace as this is not a normal textbox.

**Comment by tophf** [comment]
Makes sense. Done.

**Comment by JasonBarnabe** [comment]
Does it make sense to clear out the other filter box when you put something in one? They don't seem to work together.

I think Shift+Tab should be added to the "do normal stuff" list.

**Comment by tophf** [comment]
1. I thought so too but then decided that it's okay as-is. Do you think it does look weird now?
2. Theoretically, yes, but what its normal behavior is to focus the document outside help popup, so it's kinda strange, or not?

**Comment by JasonBarnabe** [comment]
It's a bit weird because now what happens depends on the order you did it in. Do "Alt" then "find", and you get results for "find" with "Alt" and "find" highlighted. Do "find" then "Alt", and you get results for "Alt" with "Alt" and "find" highlighted. Moreover, if you clear one of the boxes, you don't get any filtering happening at all, just highlighting. The list of keys is short enough that I don't think people need to be filtering on both at once, so having input in one box clear seems OK to me.

You can focus stuff outside the keymap pop-up with your mouse, so not really any more weird than that. I just want to avoid "trapping" people in that box. The most common ways to attempt to get out with a keystroke I think would be Tab, Shift+Tab, and Esc.

**Comment by tophf** [comment]
Very good explanation, makes perfect sense.
Done.

**Comment by JasonBarnabe** [comment]
Well now whenever the focus is lost on a filter, it clears, which isn't what I wanted either. Can you make it only clear when the other filter changes?

**Comment by tophf** [comment]
:-) Like this?

**Comment by JasonBarnabe** [comment]
It's making the other filter's highlighting not run, but the input on the other filter is still there. Additionally, when you have something entered in both filters, clearing one is not making the other active.

**Comment by tophf** [comment]
Fixed, hopefully.

**Pull request merged**
