### PR TITLE
Avoid flicker when updating applied styles

### PR DESCRIPTION
**Pull request by tophf**
Simply postpone removal of the old style element until the updated one is applied. Especially useful when editing a dark theme and frequently hitting Ctrl-S to "live-preview" the changes. I've also seen pages flicker occasionally when `webNavigation.onHistoryStateUpdated` handler was firing `styleReplaceAll` event.

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
I suppose temporarily having the old and new styles applied at the same time is better than potentially switching to none for a moment.

Can you add some comments as to what "retiring" a style does?

**Comment by tophf** [comment]
Added a comment before the `retireStyle` function.
Rebased on master.

**Comment by hideheader** [comment]
No, this isn't right at all. 

First, this is a silly "improvement". Recalculate Style takes ca. 53ms using one core of an old T7700, and Layout ca. 5ms. The "flash" when updating a dark style while it's applied is < 60ms. That's on the edge of liminal, even with monitor brightness full-on. There won't be a flash to see unless you're viewing the page whose style is being updated - a Userstyles theme updated from its Userstyles page, a Style Manager theme updated from the Style Manager, or an editor theme saved in the editor. And of course the theme must be black. Silly.

Second, this code doesn't actually fix the problem, if indeed it is a problem. You should instead `requestAnimationFrame()` and rejigger the `STYLE` elements in the callback. That way Recalculate Style, Layout, and Paint occur just once for all of the elements together instead of once per `STYLE` element.

**Comment by tophf** [comment]
Well, the PR does fix the mentioned issues and does it in a straightforward fashion with no harm whatsoever, so it's perfectly okay.

**Pull request merged**
