### PR TITLE
Reload styles on `history.pushState`

### PR DESCRIPTION
**Pull request by hideheader**
Tumblr's 'new post' buttons rewrite the current URL with `history.pushState`; they can be used with [this style](https://userstyles.org/styles/110723/test-history-pushstate-observer-tumblr) to demonstrate functionality.

Fragment identifier changes can probably be handled similarly with `onReferenceFragmentUpdated`, but I haven't a site to test against.

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
You should be able to test a fragment update on https://github.com/JasonBarnabe/stylish-chrome - just make a style for https://github.com/JasonBarnabe/stylish-chrome#contributing and then start clicking the magic header chain links.

Can you extract the badge text logic into its own function so it's not repeated?

I was going to say I was worried about flicker because all the styles are removed and then readded, but I guess Stylish does this on update anyway, and I didn't notice any problems when I added `.identity, .post-forms-glass {background: green !important;}` to the base section.

**Comment by hideheader** [comment]
(2) *Badge text.* Do you mean rehabilitate [`updateBadgeText()`](https://github.com/JasonBarnabe/stylish-chrome/blob/1a2075771d99ba4d95dbbd087f7ca3e5dace3c4d/messaging.js#L12-L28)?

(3) *Flicker.* There isn't an easy alternative to first removing all the user styles. Currently, the background script abstracts active sections from a style [[1]](https://github.com/JasonBarnabe/stylish-chrome/blob/master/background.js#L143-L145) and the content script concatenates those sections and applies them [[2]](https://github.com/JasonBarnabe/stylish-chrome/blob/master/apply.js#L49-L55). The `STYLE` gets the same `id` regardless of which sections are included, which requires side-stepping the (new &cap; old) optimization [[3]](https://github.com/JasonBarnabe/stylish-chrome/blob/master/apply.js#L37-L41) for styles such as my Tumblr example.

I handled this in 1.2.2 by adding new `STYLE`s before removing existing elements, but here I'd have to again side-step the (new &cap; old) optimization or else for example `applySections()` would leave the old, doomed version of the Tumblr style in place without adding the active version. Instead I reversed the order so that I could use `applySections()`, unmodified, instead of writing new code to apply the `STYLE`s.

**Comment by JasonBarnabe** [comment]
Not the whole previous `updateBadgeText`. It's just this logic

```js
if (details.frameId === 0 && localStorage["show-badge"] === "true") {
  chrome.browserAction.setBadgeText({text: getBadgeText(Object.keys(r)), tabId: details.tabId});
}
```
Already exists in the `onCommitted` listener. In fact the whole callback, except the `method`, is the same.

Regarding flicker, I was thinking of comparing the contents before and after if the ID already exists. But I'm fine leaving it as is until we actually see if it's going to be a problem.

**Comment by hideheader** [comment]
Done; the same callback is now used by both listeners.

**Comment by JasonBarnabe** [comment]
Great, extra functionality with only a few more lines.

**Pull request merged**
