### PR TITLE
Add Chrome shortcut keys; update all visible popups on change; add 2 prefs to toolbar button menu

### PR DESCRIPTION
**Pull request by tophf**
* **Hotkeys**
  * hotkey to open Manage styles
  * hotkey to enable/disable all styles

  No default hotkeys are assigned, to customize go to "Keyboard shortcuts" on the Extensions page

* **Toolbar button context menu** features 2 global behavior toggles:
  * show-badge pref, a new i18n label was added as it must be very short to keep the menu small
  * disableAll pref
  
  toolbarmenu

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
Can you make it "Show active style count"?

**Comment by tophf** [comment]
Thanks, it's much better. Do you mind if I amend the commit and rewrite the history?

**Comment by JasonBarnabe** [comment]
Go ahead.

**Comment by tophf** [comment]
Done.

**Pull request merged**
