### PR TITLE
Popup fixes

### PR DESCRIPTION
**Pull request by tophf**
* Fixes for Popup regressions
* autoclose after click on 'Edit' link
* ~~new option: Compact layout~~ - will be a separate PR

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
- What regressions are you fixing?
- Right-click to open the context menu, then right click again to open it again. The second time, it doesn't stay open.
- When does the pop-up not already autoclose?
- I'm unsure whether the compact layout should exist, be an option, or just be default. My main objection is that it doesn't look like you can right-click it to do anything useful, because I don't think anything else looks like that in Chrome.

**Comment by tophf** [comment]
1. regressions 
  * click style name to toggle the style
  * handle disableAll checkbox in active popup
  * actually show newly installed styles …
2. not sure I understand, here it behaves like any other context menu
3. popup isn't closed here when editor opens in a new window
4. every rightclickable element in browser doesn't look like you can rightclick it, actually, so I don't understand how this is different.

**Comment by tophf** [comment]
I've moved the compact layout commits into a separate PR.

**Comment by JasonBarnabe** [comment]
On master, using Ubuntu, switching tabs or windows closes the pop-up, so I don't see regression 1A or 1C. I also don't see anything wrong with 1B, for that matter. Maybe just an OS thing.

**Comment by tophf** [comment]
Regarding 1A (click name to toggle), the code references an old DOM path that doesn't exist now after the aligned checkboxes were put into a separate container.

1B (disableAll) doesn't strike out the styles here.

1C (show new styles) now checks `location.href` that always equals `chrome://<stylishID>/popup.html`, obviously wrong.

1a and 1b could be OS-related, I agree. Doesn't make them less useful, though :-)

**Comment by tophf** [comment]
Ah, and to see 1C: the popup should be opened, then install/add a new style in another window.

**Comment by JasonBarnabe** [comment]
Well I can't, see last comment :)

**Comment by tophf** [comment]
I don't understand how `location.href` inside popup.js can be different on Windows/Linux. The code was clearly wrong.

**Comment by JasonBarnabe** [comment]
Not saying that aspect is different, I'm saying I can't trigger the bug because the pop-up closes when I focus another window.

**Comment by tophf** [comment]
Ah, I get it now. However a concealed bug is a bug anyway, and on Windows I see it.

**Pull request merged**
