### PR TITLE
Apply styles to own pages earlier to avoid flicker

### PR DESCRIPTION
**Pull request by tophf**
This removes momentary flashing of the original unstyled content on "Manage styles" and "Edit style" when custom styles for these pages are used.

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
Can you refactor so the arguments to function are not repeated?

**Comment by tophf** [comment]
I didn't want to introduce any new global functions or variables, that's why.
What about this:

```js
(function() {
	var request = {method: "getStyles", matchUrl: location.href, enabled: true, asHash: true};
	if (location.href.indexOf(chrome.extension.getURL("")) == 0) {
		chrome.extension.getBackgroundPage().getStyles(request, applyStyles);
	} else {
		chrome.extension.sendMessage(request, applyStyles);
	}
})();
```

**Comment by JasonBarnabe** [comment]
I'm not concerned about globals.

**Comment by tophf** [comment]
Updated.

**Pull request merged**
