### PR TITLE
Implement site exclusions

### LINKED ISSUE #141: UI feature to exclude specified sites from a global style
Although it's possible to write negative lookahead regexps in style code but Tampermonkey, Greasemonkey have %subj% for years.

### PR DESCRIPTION
**Pull request by tophf**
Closes #141 

Adds site exclusion option and a textbox to list the excluded sites.

One site per line using autodetect of syntax:
- domain - only alphanumeric and dots/hyphens: `google-shmoogle.com`
- regexp - `/` at both the start and the end, optional flag `i` is supported: `/google\\.\\w{2,3}(.\\w{2,3})?\\/.*\\/inbox.*/";`
- URL - prefix starts with http/https/ftp and ends with `*`: https://google.com/mail/*
- URL - everything else `https://www.google.com/webhp`

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
While this is useful, I've made it a policy to keep the differences between browsers as little as possible, even if that means a somewhat worse experience in each. This in particular will lead people to want to share the styles, which means that they'll want to post to userstyles.org, which won't work with any other browser.

**Comment by tophf** [comment]
The exclusions aren't part of the style so it won't break on userstyles.org if this was your concern.

**Comment by tophf** [comment]
BTW, in Greasemonkey and Tampermonkey this feature was always a personal preference that has absolutely nothing to do with the code. The same here. As for Stylish Firefox, simply add this feature in your usual tempo, people will understand if it takes 5 years, or maybe someone will add it, which should happen once they see how bleak their user experience was before :-)

**Comment by tophf** [comment]
How about a more verbose label `Don't apply on specified sites. This is a local setting and isn't part of the style`?

**Comment by tophf** [comment]
Or make it even more obvious by showing it as a titled separate section when the checkbox is enabled, the checkbox itself will be in a more expected position under `[x] enabled`:

ui2-fs8

**Comment by tophf** [comment]
Implemented & re-pushed.

**Comment by tophf** [comment]
More ideas:

1. This option may be dynamic and only shown for global styles...
2. Toolbar popup may show an exclusion menu (exclude -> domain, exact URL, URL prefix) if a global style is applied currently to the page

**Comment by JasonBarnabe** [comment]
Could instead make this kind of a exclusion regex generator, where some enters a domain and a URL to not affect and it makes the regex for them? That would be compatible with everyone else.

**Comment by tophf** [comment]
The goal is to make the feature *user-friendly* so such generator would have to:

1. decode the existing regexps from global sections and show them in a human-readable list
2. the human-readable list would have to be automatically synchronized to regexps and vice versa, but this would be a problem when there are several global sections

**Comment by JasonBarnabe** [comment]
What URLs a style applies to is part of the style, not a local option. If I have word wrap on, I can still share my styles with everyone else. The same is not true for this.

With generated regexps, I'm thinking the exception list would be specific to each section. I also think you could keep track of stuff for parsing with named groups or comments inside the regexp.

**Comment by tophf** [comment]
Nah, the site exclusions aren't part of style. Users of a global style exclude some sites based purely on their personal preference.

**Comment by JasonBarnabe** [comment]
I'm still of the opinion that the sites that a style shouldn't affect is properly part of the code of the style. If you add this as a "personal preference", people are going to start asking how they can post it on userstyles.org and maintain the preferences. In other words, people aren't going to look at this as personal preferences. It's just going to cause problems.

**Comment by tophf** [comment]
But this model successfully works for Greasemonkey/Tampermonkey and I don't see disappointed users...

**Comment by JasonBarnabe** [comment]
Because GM also allows it as part of the script.

**Comment by tophf** [comment]
GM/TM have `@exclude` indeed but it doesn't change anything. The users locally exclude the sites via TM/GM user interface, not by editing a userscript. The same could be implemented in Stylish. As I suggested the exclusion block may be positioned and named so that there would be no confusion.

**Comment by tophf** [comment]
Also we can add an option to export those exclusion to moz-format.

**Pull request closed without merging**
